/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountSection } from './AccountSection';
import {
    AccountSectionFromJSON,
    AccountSectionFromJSONTyped,
    AccountSectionToJSON,
} from './AccountSection';

/**
 * 
 * @export
 * @interface AccountSectionsList200Response
 */
export interface AccountSectionsList200Response {
    /**
     * 
     * @type {number}
     * @memberof AccountSectionsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof AccountSectionsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccountSectionsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AccountSection>}
     * @memberof AccountSectionsList200Response
     */
    results: Array<AccountSection>;
}

/**
 * Check if a given object implements the AccountSectionsList200Response interface.
 */
export function instanceOfAccountSectionsList200Response(value: object): value is AccountSectionsList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function AccountSectionsList200ResponseFromJSON(json: any): AccountSectionsList200Response {
    return AccountSectionsList200ResponseFromJSONTyped(json, false);
}

export function AccountSectionsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSectionsList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AccountSectionFromJSON)),
    };
}

export function AccountSectionsList200ResponseToJSON(value?: AccountSectionsList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AccountSectionToJSON)),
    };
}

