/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Category } from './Category';
import {
    CategoryFromJSON,
    CategoryFromJSONTyped,
    CategoryToJSON,
} from './Category';

/**
 * 
 * @export
 * @interface CategoryList200Response
 */
export interface CategoryList200Response {
    /**
     * 
     * @type {number}
     * @memberof CategoryList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CategoryList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Category>}
     * @memberof CategoryList200Response
     */
    results: Array<Category>;
}

/**
 * Check if a given object implements the CategoryList200Response interface.
 */
export function instanceOfCategoryList200Response(value: object): value is CategoryList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function CategoryList200ResponseFromJSON(json: any): CategoryList200Response {
    return CategoryList200ResponseFromJSONTyped(json, false);
}

export function CategoryList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(CategoryFromJSON)),
    };
}

export function CategoryList200ResponseToJSON(value?: CategoryList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(CategoryToJSON)),
    };
}

