/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
} from './Document';

/**
 * 
 * @export
 * @interface DocumentsList200Response
 */
export interface DocumentsList200Response {
    /**
     * 
     * @type {number}
     * @memberof DocumentsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof DocumentsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Document>}
     * @memberof DocumentsList200Response
     */
    results: Array<Document>;
}

/**
 * Check if a given object implements the DocumentsList200Response interface.
 */
export function instanceOfDocumentsList200Response(value: object): value is DocumentsList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function DocumentsList200ResponseFromJSON(json: any): DocumentsList200Response {
    return DocumentsList200ResponseFromJSONTyped(json, false);
}

export function DocumentsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentsList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(DocumentFromJSON)),
    };
}

export function DocumentsList200ResponseToJSON(value?: DocumentsList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(DocumentToJSON)),
    };
}

