/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KodVida
 */
export interface KodVida {
    /**
     * 
     * @type {number}
     * @memberof KodVida
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof KodVida
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof KodVida
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof KodVida
     */
    razdel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KodVida
     */
    description?: string | null;
}

/**
 * Check if a given object implements the KodVida interface.
 */
export function instanceOfKodVida(value: object): value is KodVida {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function KodVidaFromJSON(json: any): KodVida {
    return KodVidaFromJSONTyped(json, false);
}

export function KodVidaFromJSONTyped(json: any, ignoreDiscriminator: boolean): KodVida {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'code': json['code'],
        'razdel': json['razdel'] == null ? undefined : json['razdel'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function KodVidaToJSON(value?: Omit<KodVida, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'code': value['code'],
        'razdel': value['razdel'],
        'description': value['description'],
    };
}

