/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KodVida } from './KodVida';
import {
    KodVidaFromJSON,
    KodVidaFromJSONTyped,
    KodVidaToJSON,
} from './KodVida';

/**
 * 
 * @export
 * @interface KodvidaList200Response
 */
export interface KodvidaList200Response {
    /**
     * 
     * @type {number}
     * @memberof KodvidaList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof KodvidaList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof KodvidaList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<KodVida>}
     * @memberof KodvidaList200Response
     */
    results: Array<KodVida>;
}

/**
 * Check if a given object implements the KodvidaList200Response interface.
 */
export function instanceOfKodvidaList200Response(value: object): value is KodvidaList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function KodvidaList200ResponseFromJSON(json: any): KodvidaList200Response {
    return KodvidaList200ResponseFromJSONTyped(json, false);
}

export function KodvidaList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KodvidaList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(KodVidaFromJSON)),
    };
}

export function KodvidaList200ResponseToJSON(value?: KodvidaList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(KodVidaToJSON)),
    };
}

