/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Orgitem } from './Orgitem';
import {
    OrgitemFromJSON,
    OrgitemFromJSONTyped,
    OrgitemToJSON,
} from './Orgitem';

/**
 * 
 * @export
 * @interface OrgitemList200Response
 */
export interface OrgitemList200Response {
    /**
     * 
     * @type {number}
     * @memberof OrgitemList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof OrgitemList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrgitemList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Orgitem>}
     * @memberof OrgitemList200Response
     */
    results: Array<Orgitem>;
}

/**
 * Check if a given object implements the OrgitemList200Response interface.
 */
export function instanceOfOrgitemList200Response(value: object): value is OrgitemList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function OrgitemList200ResponseFromJSON(json: any): OrgitemList200Response {
    return OrgitemList200ResponseFromJSONTyped(json, false);
}

export function OrgitemList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrgitemList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(OrgitemFromJSON)),
    };
}

export function OrgitemList200ResponseToJSON(value?: OrgitemList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(OrgitemToJSON)),
    };
}

