/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Person } from './Person';
import {
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
} from './Person';

/**
 * 
 * @export
 * @interface PersonList200Response
 */
export interface PersonList200Response {
    /**
     * 
     * @type {number}
     * @memberof PersonList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PersonList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Person>}
     * @memberof PersonList200Response
     */
    results: Array<Person>;
}

/**
 * Check if a given object implements the PersonList200Response interface.
 */
export function instanceOfPersonList200Response(value: object): value is PersonList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PersonList200ResponseFromJSON(json: any): PersonList200Response {
    return PersonList200ResponseFromJSONTyped(json, false);
}

export function PersonList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(PersonFromJSON)),
    };
}

export function PersonList200ResponseToJSON(value?: PersonList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(PersonToJSON)),
    };
}

