/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountSection
 */
export interface AccountSection {
    /**
     * 
     * @type {number}
     * @memberof AccountSection
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof AccountSection
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof AccountSection
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof AccountSection
     */
    accountNumber: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSection
     */
    initialBalance: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSection
     */
    totalReceived: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSection
     */
    totalWithdrawn: string;
    /**
     * 
     * @type {string}
     * @memberof AccountSection
     */
    finalBalance: string;
}

/**
 * Check if a given object implements the AccountSection interface.
 */
export function instanceOfAccountSection(value: object): value is AccountSection {
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('initialBalance' in value) || value['initialBalance'] === undefined) return false;
    if (!('totalReceived' in value) || value['totalReceived'] === undefined) return false;
    if (!('totalWithdrawn' in value) || value['totalWithdrawn'] === undefined) return false;
    if (!('finalBalance' in value) || value['finalBalance'] === undefined) return false;
    return true;
}

export function AccountSectionFromJSON(json: any): AccountSection {
    return AccountSectionFromJSONTyped(json, false);
}

export function AccountSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountSection {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'accountNumber': json['account_number'],
        'initialBalance': json['initial_balance'],
        'totalReceived': json['total_received'],
        'totalWithdrawn': json['total_withdrawn'],
        'finalBalance': json['final_balance'],
    };
}

export function AccountSectionToJSON(value?: Omit<AccountSection, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start_date': ((value['startDate']).toISOString().substring(0,10)),
        'end_date': ((value['endDate']).toISOString().substring(0,10)),
        'account_number': value['accountNumber'],
        'initial_balance': value['initialBalance'],
        'total_received': value['totalReceived'],
        'total_withdrawn': value['totalWithdrawn'],
        'final_balance': value['finalBalance'],
    };
}

