/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Product } from './Product';
import {
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './Product';

/**
 * 
 * @export
 * @interface ProductsList200Response
 */
export interface ProductsList200Response {
    /**
     * 
     * @type {number}
     * @memberof ProductsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof ProductsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Product>}
     * @memberof ProductsList200Response
     */
    results: Array<Product>;
}

/**
 * Check if a given object implements the ProductsList200Response interface.
 */
export function instanceOfProductsList200Response(value: object): value is ProductsList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function ProductsList200ResponseFromJSON(json: any): ProductsList200Response {
    return ProductsList200ResponseFromJSONTyped(json, false);
}

export function ProductsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProductFromJSON)),
    };
}

export function ProductsList200ResponseToJSON(value?: ProductsList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProductToJSON)),
    };
}

