/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RegdocList } from './RegdocList';
import {
    RegdocListFromJSON,
    RegdocListFromJSONTyped,
    RegdocListToJSON,
} from './RegdocList';

/**
 * 
 * @export
 * @interface RegdocsList200Response
 */
export interface RegdocsList200Response {
    /**
     * 
     * @type {number}
     * @memberof RegdocsList200Response
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof RegdocsList200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegdocsList200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RegdocList>}
     * @memberof RegdocsList200Response
     */
    results: Array<RegdocList>;
}

/**
 * Check if a given object implements the RegdocsList200Response interface.
 */
export function instanceOfRegdocsList200Response(value: object): value is RegdocsList200Response {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function RegdocsList200ResponseFromJSON(json: any): RegdocsList200Response {
    return RegdocsList200ResponseFromJSONTyped(json, false);
}

export function RegdocsList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegdocsList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RegdocListFromJSON)),
    };
}

export function RegdocsList200ResponseToJSON(value?: RegdocsList200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RegdocListToJSON)),
    };
}

