/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Regdoc
 */
export interface Regdoc {
    /**
     * 
     * @type {number}
     * @memberof Regdoc
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    rznId?: string;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    ruNumber?: string;
    /**
     * 
     * @type {Date}
     * @memberof Regdoc
     */
    regDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Regdoc
     */
    expDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    ruBody?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    ruStatus?: RegdocRuStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    manufacturerRepName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    manufacturerRepLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    manufacturerRepLegalAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    manufacturerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    manufacturerLocation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    manufacturerLegalAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    okpOkpd2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    riskClass?: string;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    devicePurpose?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    productionAddress?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    ruBodyTsv?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Regdoc
     */
    code: string;
}


/**
 * @export
 */
export const RegdocRuStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Dateout: 'dateout',
    Frozen: 'frozen'
} as const;
export type RegdocRuStatusEnum = typeof RegdocRuStatusEnum[keyof typeof RegdocRuStatusEnum];


/**
 * Check if a given object implements the Regdoc interface.
 */
export function instanceOfRegdoc(value: object): value is Regdoc {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function RegdocFromJSON(json: any): Regdoc {
    return RegdocFromJSONTyped(json, false);
}

export function RegdocFromJSONTyped(json: any, ignoreDiscriminator: boolean): Regdoc {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'rznId': json['rzn_id'] == null ? undefined : json['rzn_id'],
        'ruNumber': json['ru_number'] == null ? undefined : json['ru_number'],
        'regDate': json['reg_date'] == null ? undefined : (new Date(json['reg_date'])),
        'expDate': json['exp_date'] == null ? undefined : (new Date(json['exp_date'])),
        'ruBody': json['ru_body'] == null ? undefined : json['ru_body'],
        'ruStatus': json['ru_status'] == null ? undefined : json['ru_status'],
        'manufacturerRepName': json['manufacturer_rep_name'] == null ? undefined : json['manufacturer_rep_name'],
        'manufacturerRepLocation': json['manufacturer_rep_location'] == null ? undefined : json['manufacturer_rep_location'],
        'manufacturerRepLegalAddress': json['manufacturer_rep_legal_address'] == null ? undefined : json['manufacturer_rep_legal_address'],
        'manufacturerName': json['manufacturer_name'] == null ? undefined : json['manufacturer_name'],
        'manufacturerLocation': json['manufacturer_location'] == null ? undefined : json['manufacturer_location'],
        'manufacturerLegalAddress': json['manufacturer_legal_address'] == null ? undefined : json['manufacturer_legal_address'],
        'okpOkpd2': json['okp_okpd2'] == null ? undefined : json['okp_okpd2'],
        'riskClass': json['risk_class'] == null ? undefined : json['risk_class'],
        'devicePurpose': json['device_purpose'] == null ? undefined : json['device_purpose'],
        'productionAddress': json['production_address'] == null ? undefined : json['production_address'],
        'ruBodyTsv': json['ru_body_tsv'] == null ? undefined : json['ru_body_tsv'],
        'code': json['code'],
    };
}

export function RegdocToJSON(value?: Omit<Regdoc, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rzn_id': value['rznId'],
        'ru_number': value['ruNumber'],
        'reg_date': value['regDate'] == null ? undefined : ((value['regDate'] as any).toISOString().substring(0,10)),
        'exp_date': value['expDate'] == null ? undefined : ((value['expDate'] as any).toISOString().substring(0,10)),
        'ru_body': value['ruBody'],
        'ru_status': value['ruStatus'],
        'manufacturer_rep_name': value['manufacturerRepName'],
        'manufacturer_rep_location': value['manufacturerRepLocation'],
        'manufacturer_rep_legal_address': value['manufacturerRepLegalAddress'],
        'manufacturer_name': value['manufacturerName'],
        'manufacturer_location': value['manufacturerLocation'],
        'manufacturer_legal_address': value['manufacturerLegalAddress'],
        'okp_okpd2': value['okpOkpd2'],
        'risk_class': value['riskClass'],
        'device_purpose': value['devicePurpose'],
        'production_address': value['productionAddress'],
        'ru_body_tsv': value['ruBodyTsv'],
        'code': value['code'],
    };
}

