/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegdocList
 */
export interface RegdocList {
    /**
     * 
     * @type {number}
     * @memberof RegdocList
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof RegdocList
     */
    ruNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof RegdocList
     */
    manufacturerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegdocList
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof RegdocList
     */
    ruBody?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegdocList
     */
    ruStatus?: RegdocListRuStatusEnum;
}


/**
 * @export
 */
export const RegdocListRuStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Dateout: 'dateout',
    Frozen: 'frozen'
} as const;
export type RegdocListRuStatusEnum = typeof RegdocListRuStatusEnum[keyof typeof RegdocListRuStatusEnum];


/**
 * Check if a given object implements the RegdocList interface.
 */
export function instanceOfRegdocList(value: object): value is RegdocList {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function RegdocListFromJSON(json: any): RegdocList {
    return RegdocListFromJSONTyped(json, false);
}

export function RegdocListFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegdocList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'ruNumber': json['ru_number'] == null ? undefined : json['ru_number'],
        'manufacturerName': json['manufacturer_name'] == null ? undefined : json['manufacturer_name'],
        'code': json['code'],
        'ruBody': json['ru_body'] == null ? undefined : json['ru_body'],
        'ruStatus': json['ru_status'] == null ? undefined : json['ru_status'],
    };
}

export function RegdocListToJSON(value?: Omit<RegdocList, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ru_number': value['ruNumber'],
        'manufacturer_name': value['manufacturerName'],
        'code': value['code'],
        'ru_body': value['ruBody'],
        'ru_status': value['ruStatus'],
    };
}

