/* tslint:disable */
/* eslint-disable */
/**
 * Your Project API
 * API documentation for your project
 *
 * The version of the OpenAPI document: v1
 * Contact: contact@yourproject.local
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRefreshResponse
 */
export interface TokenRefreshResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenRefreshResponse
     */
    access: string;
}

/**
 * Check if a given object implements the TokenRefreshResponse interface.
 */
export function instanceOfTokenRefreshResponse(value: object): value is TokenRefreshResponse {
    if (!('access' in value) || value['access'] === undefined) return false;
    return true;
}

export function TokenRefreshResponseFromJSON(json: any): TokenRefreshResponse {
    return TokenRefreshResponseFromJSONTyped(json, false);
}

export function TokenRefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRefreshResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'access': json['access'],
    };
}

export function TokenRefreshResponseToJSON(value?: TokenRefreshResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'access': value['access'],
    };
}

